// Get Products
export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED';
export const GET_PRODUCTS_SUCCEEDED = 'GET_PRODUCTS_SUCCEEDED';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

// Get Product Details
export const GET_PRODUCT_DETAILS_STARTED = 'GET_PRODUCT_DETAILS_STARTED';
export const GET_PRODUCT_DETAILS_SUCCEEDED = 'GET_PRODUCT_DETAILS_SUCCEEDED';
export const GET_PRODUCT_DETAILS_FAILED = 'GET_PRODUCT_DETAILS_FAILED';

// create Product
export const GET_CREATE_PRODUCT_STARTED = 'GET_CREATE_PRODUCT_STARTED';
export const GET_CREATE_PRODUCT_SUCCEEDED = 'GET_CREATE_PRODUCT_SUCCEEDED';
export const GET_CREATE_PRODUCT_FAILED = 'GET_CREATE_PRODUCT_FAILED';

// remove Product
export const REMOVE_PRODUCT_STARTED = 'REMOVE_PRODUCT_STARTED';
export const REMOVE_PRODUCT_SUCCEEDED = 'REMOVE_PRODUCT_SUCCEEDED';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';

// Get Categories
export const GET_CATEGORIES_STARTED = 'GET_CATEGORIES_STARTED';
export const GET_CATEGORIES_SUCCEEDED = 'GET_CATEGORIES_SUCCEEDED';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
