// Get Items

export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED";
export const GET_ITEMS_SUCCEEDED = "GET_ITEMS_SUCCEEDED";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";

// Add to Cart

export const ADD_TO_CART_ITEM_STARTED = "ADD_TO_CART_ITEM_STARTED";
export const ADD_TO_CART_ITEM_SUCCEEDED = "ADD_TO_CART_ITEM_SUCCEEDED";
export const ADD_TO_CART_ITEM_FAILED = "ADD_TO_CART_ITEM_FAILED";

// Remove Cart
export const REMOVE_TO_CART_ITEM_STARTED = "REMOVE_TO_CART_ITEM_STARTED";
export const REMOVE_TO_CART_ITEM_SUCCEEDED = "REMOVE_TO_CART_ITEM_SUCCEEDED";
export const REMOVE_TO_CART_ITEM_FAILED = "REMOVE_TO_CART_ITEM_FAILED";

// Get Product Type
export const GET_PRODUCTS_STARTED = "GET_PRODUCTS_STARTED";
export const GET_PRODUCTS_SUCCEEDED = "GET_PRODUCTS_SUCCEEDED";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

// Get Product Details
export const GET_PRODUCT_DETAILS_STARTED = "GET_PRODUCT_DETAILS_STARTED";
export const GET_PRODUCT_DETAILS_SUCCEEDED = "GET_PRODUCT_DETAILS_SUCCEEDED";
export const GET_PRODUCT_DETAILS_FAILED = "GET_PRODUCT_DETAILS_FAILED";
